version: '2'
services:
  mono2-postgresql:
    image: postgres:12.3
    # volumes:
    #     - ~/volumes/jhipster/mono2/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mono2
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
